name = "lingyuetool-rss-magnet"
main = "worker/index.js"
compatibility_date = "2026-07-03"
workers_dev = true

[vars]
DEEPSEEK_BASE_URL = "https://api.deepseek.com"
DEEPSEEK_MODEL = "deepseek-v4-flash"

[[routes]]
pattern = "lingyuetools.org"
zone_id = "b6b7ae277e7d2d48144eae81109fed4e"
custom_domain = true

[[routes]]
pattern = "www.lingyuetools.org"
zone_id = "b6b7ae277e7d2d48144eae81109fed4e"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "lingyuetools-db"
database_id = "044f6770-c615-4c6a-b2bb-60a91dcf27bb"
migrations_dir = "migrations"
